#+TODO: TODO(t) IN-PROGRESS(i) | DONE(d)
#+latex_header: \usepackage[citestyle=authoryear,bibstyle=authoryear,hyperref=true,backref=true,maxcitenames=3,url=true,backend=biber,natbib=true] {biblatex}
#+latex_header: \addbibresource{/home/matt/Dropbox/BibLaTeX/library.bib}
#+BEGIN_SRC clojure :results value
agent-num
#+END_SRC

#+RESULTS:
: 200

# Start document
Possible title: Sympathy for the Noise Trader
* Need code to do the following:
** TODO Vector for both value and information signal, even though the price is still a sum down the vector. Thinking: everyone gets a vector, informed people get one piece of the vector filled in with the correct value, update and guess on the rest. Uninformed people guess everywhere and randomly pick an element of the vector when they update. (Possible alternative: have everyone collect only one piece of information, and have the market aggregate? Not exactly what I was thinking, but could be interesting.) Question: do you converge on the correct value? Could be interesting on its own. If you do, how long does it take?
*** TODO Also consider OLS updating for all cases (univariate and multivariate) and, if possible without blowing up the information space, Bayesian updating.
*** TODO Have to fix the updating of a prior: right now I move closer to price on the one prior, should move closer to price MINUS rest of vector (for expectation of that prior holding other elements constant.
** TODO A way to iterate the market, with uninformed investors rolling their updated priors over from iteration to iteration. Or the "final" market price. Also need a way to decide when to stop the market, perhaps when the rounded value doesn't change for a certain number of periods or until the sum of changes for a certain number of periods equals zero.
** IN-PROGRESS Also will need an elegant way to visualize multi-dimensional priors and multiple market periods. Maybe for multi-dimensional priors the main visualization is still based on "guessed" price and then a second visualization in two and three dimensions showing dispersion in individual priors.
** DONE Make functions modular in order to be able to pass in new functions quickly. Especially true for agent updating: I would like to implement OLS and Bayesian updating as well as "simple" updating.
   CLOSED: [2019-08-23 Fri 14:47]

* Thoughts for paper
RQ: We often talk about "learning from price" in what I think is a sloppy way (have to find example). In finance (G&S, for example) they tend to treat the learning problem as one of a single distribution, that of price itself, and think of informational signals as combining into a single multivariate normal distribution. In essence, investors do not need to learn about parameters from price: they just learn directly about price from price. This seems like weak form efficiency: you can't make money trading on prior patterns in price because you are supposed to be able to learn from them. I have to revisit the early literature on "rational expectations" in accounting, but it seems like this is a very different thing from the semi-strong and strong forms of market efficiency in which all available information is impounded in price. In those forms, either 1) everyone simply becomes fully informed on their own; 2) individuals becoming informed are able to make sensible trading decisions about how their information informs price without knowing everything and then it all gets aggregated (like in cite:verrecchiaConsensusBeliefsInformation1980, with a univariate distribution but different draws); or 3) they must somehow learn from price. The first option seems nonsensical given the quantity of information, the limits on human information processing, and the speed with which we often treat price formation. The second does not seem to work in a multivariate setting. The third (and somewhat the second) is what I am exploring.




\printbibliography

* Literature review on price formation and rational expectations
** From cite:leeMarketEfficiencyAccounting2001: A more measured, and more descriptive, statement is that the ocean is constantly trying to become flat. In reality, market prices are buffeted by a continuous flow of information, or rumors and innuendos disguised as information. Individuals reacting to these signals, or pseudo-signals, 4 cannot fully calibrate the extent to which their own signal is already reflected in price. Prices move as they trade on the basis of their imperfect informational endowments. Eventually, through trial and error, the aggregation process is completed and prices adjust to fully reveal the impact of a particular signal. But by that time, many new signals have arrived, causing new turbulence. As a result, the ocean is in a constant state of restlessness. The market is in a continuous state of adjustment.
** From cite:kothariCapitalMarketsResearch2001: Fortunately, several excellent surveys of the market efficiency literature exist. I encourage interested researchers to read Ball (1978, 1992, 1994), Fama (1970, 1991, 1998), LeRoy (1989), MacKinlay (1997), and Campbell et al. (1997).
** From cite:grossmanEfficiencyCompetitiveStock1976, pg. 3: Hayek [1945] argues that the essence of a competitive price system is that when a commodity becomes scarce its price rises and this induces people to consume less of the commodity and to invest more in the production of the commodity. Individuals need not know why the price has risen, the fact that there is a higher price induces them to counteract the scarcity in an efficient way. This argument breaks down when the price system is noisy. We will show that in such cases each individual wants to know why the price has risen (i.e., what exogenous factors make the price unusually high), and that an optimal allocation of resources involves knowing why the price has risen (i.e., knowledge of the states of nature determining current prices is required).
** From cite:segalAreManagersStrategic2016: Furthermore, managers can also mitigate market reaction to negative events by bundling news of opposite signs.
*** I'm not sure this is true; if my theory is correct regarding bundling, then the signal just gets obscured. So it could be more positive, more negative, or neither. On the other hand, maybe this is right; because the positive offsets the negative, everyone adjusts by less. Kind of depends on the magnitude of the adjustment that an investor "defaults" to...
** From cite:leeActiveFundsBundled2019: A second reason to study AMF reaction to earnings news stems from the broader issue of market efficiency. The issue of whether institutional investors help correct market mispricing has been widely debated. Some evidence suggests that institutional investors fail to take advantage of various pricing anomalies, and in some cases may even exacerbate them (Lewellen 2011; Edelen et al. 2016). Other studies find that higher institutional trading or ownership, and greater institutional attention to news, can improve price discovery. For example, Henry and Koski (2017) find that institutions earn higher profits around ex-dividend event days. Cheng, Hameed, Subrahmanyam, and Titman (2017) find that the magnitudes of short-term return reversals are higher following declines in the number of active institutional investors. Similarly, Bartov, Radhakrishnan, and Krinsky (2000) report that the level of institutional ownership is negatively correlated with the size of the post-earnings announcement drift (PEAD). Stocks with increases in mutual fund holdings have higher subsequent EA returns (Baker et al. 2010). In addition, greater institutional attention, as measured by Bloomberg terminal searches and the number of news reads, has also been associated with improved price discovery (Ben-Rephael, Da, and Israelsen 2017). However, none of these studies investigate the role of AMF trading in response to earnings news. We contribute to this literature by using detailed trade-level data to evaluate the role of AMFs in the price discovery process associated with earnings news. Specifically, we examine three related hypotheses. First, if AMF participation improves overall price discovery, then, ceteris paribus, we expect the EAs with greater abnormal AMF participation to exhibit faster and more complete price adjustments than EAs with little or no abnormal AMF participation. Specifically, we hypothesize that increased AMF trading during EAs leads to faster price convergence and reduced post-EA price drift. Second, we hypothesize that the directional (buy minus sell) trades of AMFs will generally ameliorate price drifts – that is, we expect net directional trading by AMFs shift returns from the post-EA period to the EA period. Finally, we conduct a detailed comparison of EA vs non-EA trades, controlling for the specific AMF in question. To the extent that AMFs have an informational advantage in processing the value implications of earnings news, we expect their EA period trades to be more profitable than their non-EA trades.
* Introduction
Since accounting is an information science, accounting researchers spend a great deal of ink on information: who has it, how it is communicated and spread and how it is processed for decision-making. One of the most central ideas in both accounting and finance is that market price itself is a major information discovery mechanism: through trading, investors reveal their private information to other investors. However, investors are only able to communicate their information through buy and sell decisions, essentially a binary indicator about whether the investor's private information indicates a higher or a lower price. Consistent with the analytical literature (such as Grossman and Stiglitz or Verrecchia, put cites in later) and simulation work based on these models (cite the guy who simulated G&S), in which the combination of investors' private signals converges to the true mean of a single distribution, I find that this signal is sufficient. However, this structure is only sufficient if investors care only to learn about price, i.e. weak-form market efficiency, in which investors cannot profit from observing prior patterns in price. For semi-strong or strong form market efficiency, investors must be able to learn individually about a vector of inputs, by observing the movement of only a single number. In this paper, I conduct a simulation to determine the limits of learning from price when multiple signals are available.

In my model, agents are either uninformed, in which case they are assigned a random prior, or informed about an element of the vector that should determine "true" price. When the information vector is only one element long, then, only uninformed investors update their beliefs; informed investors know the true value and do not deviate. This setup mirrors the Grossman and Stiglitz model and, similar to that model and the simulation by (X), I find that over time uninformed investors are able to learn the true distribution of value and trade accordingly, reducing the value of being informed. This result, however, depends on a large enough percentage of investors being informed for them to dominate trading; otherwise, price can converge to the (incorrect) mean of uninformed traders' priors. This replicates the paradox highlighted in Grossman and Stiglitz, in which informed investors are necessary but realize diminishing returns from the cost of information collection.

I then extend the model to include multiple information signals, with "true" value determined by the sum of the realizations of each signal. For simplicity, each informed investor is only informed about a single information signal. However, the signal assigned to each investor is random, so there is a roughly even proportion of informed traders for each signal. Uninformed investors receive a vector of random draws. In this case, I find... (note to self: if I find fixation on the "known" signal for clusters of investors, then cite earnings fixation literature).

My study contributes to prior literature by examining how investors learn from price when they cannot perfectly infer that the price movement pertains to a particular information signal. This environment mirrors that faced by researchers: it is difficult to infer how investors respond to earnings, for example, when the earnings disclosure is combined, not only with other management disclosures such as textual reports and forecasts, but other sources of information such as analyst commentary and the business press. This ambiguity forces investors to look for other means of determining how to interpret price response, which can lead to... In my study, agents using "social media" to communicate with one another are better able to process the price signal, suggesting that social media is important for disseminating, not just information, but how investors are trading on that information (Pasquariello and Wang could be useful here.)

I also contribute to future literature by providing a framework, licensed under the Creative Commons, for future researchers to replicate, stress-test and extend my results. Simulations are prime opportunities for this kind of information sharing, since they rely on few external sources of information. My code is written in a Lisp dialect, Clojure, that makes it easy to modify and extend by creating new agent and market creation and updating mechanisms. Since the Creative Commons license requires anyone using the code to make their modifications publicly available, I hope that future researchers will be able to go directly to the source when creating their own simulations, saving researcher time and encouraging collaboration.
* Literature Review and Hypothesis Development
  :PROPERTIES:
  :CUSTOM_ID: litreview
  :END:
* Model
In my model, informed investors are fully informed in the single parameter case and uninformed investors learn from price. Uninformed investors can also learn the true distribution of the unobservable parameter through repeated market interactions: as in cite:grossmanEfficiencyCompetitiveStock1976, the price to which the market converges represents a draw from the true distribution. This leads to the famous paradox that profits from becoming informed decline over time, to the point where there is no market equilibrium when information is costly (see [[#litreview][Literature Review]] alt link [[#litreview]]). 
When informed traders are allowed only to learn one parameter, they can approximate uninformed traders in the two-parameter case, in which they can learn perfectly from price because they always update only one parameter (is this true?)
For three parameters and more, since I only allow informed traders to know one parameter, they are in the same boat as uninformed traders in that they have to learn more than one parameter from one signal (although they converge more quickly because they have fewer parameters to learn (?)). This can approximate real-world markets in which the majority of participants lack the cognitive or financial resources to become fully informed. In this case, the social media outcome benefits even informed traders and gives them an incentive to share their information in exchange for information. Same problem as in Grossman, where everyone wants to benefit from the environment but where no one wants to contribute? What sustains equilibrium? Also might want to footnote trust mechanisms (cite own RAST paper) that keep people honest in their communications).
